# DQN Learning parameters
learning_rate: 0.0001
policy_kwargs:
  net_arch:
    - 256
    - 256

# Replay buffer parameters
learning_starts: 10000
batch_size: 128

# Train Frequency parameters
train_freq: 4
gradient_steps: 1
target_update_interval: 10000

# Epsilon-greedy parameters for exploration vs exploitation
exploration_initial_eps: 1.0
exploration_final_eps: 0.02
exploration_fraction: 0.2

# Other parameters
gamma: 0.99
